---
title: "Caregiver Pailot data"
author: "Mukter"
date: "`r Sys.Date()`"
output: html_document
---




```{r}

library(readxl)
library(foreign)
library(haven)
library(dplR)
library(tidyverse)
library(labelled)
library(gtsummary)
library(gt)
library(lubridate)
library(gt)
library(dplyr)
library(openxlsx)
library(officer)
library(flextable)
library(rmarkdown)
library(knitr)
library(psych)
library(ggplot2)
library(lubridate)
library(labelled)
library(haven)

```


## Open the data set

```{r}
Caregiver_36Months_data <- read_dta("H:/.shortcut-targets-by-id/10GfELvbVWTnThBtJs-WKEAmKwWDCBjeu/Clean Dataset/2_Data_file/Caregiver_36Months_data.dta")


```

### Surevey duration time 

```{r}
# Convert to POSIXct and calculate duration

Caregiver_36Months_data <- Caregiver_36Months_data  %>% 
  mutate(
    survey_s_time1 = parse_date_time(survey_s_time, orders = "I:M:S p"),
    survey_e_time1 = parse_date_time(survey_e_time, orders = "I:M:S p"),
    duration_minutes = as.numeric(difftime(survey_e_time1, survey_s_time1, units = "mins"))
  )




View(Caregiver_36Months_data %>% select(survey_s_time,survey_e_time,duration_minutes,survey_date,enu,fcn_no))
```



### Show all section start & ENd time

```{r}

View(Caregiver_36Months_data %>% select(education_s_t ,education_e_t, environment_s_t ,environment_e_t, asset_s_t, asset_e_t, health_stat_s_t, health_stat_e_t, ecdprograms_s_t, ecdprograms_e_t, socialsup_s_t ,socialsup_e_t, mva_s_t_m ,mva_e_t_m ,htq4_s_time ,htq4_e_t ,function_s_t, function_e_t, ref_function_s_t, ref_function_e_t, psqi_s_t, psqi_e_t, rmhm_s_t, rmhm_e_t, stressors_s_time, stressors_e_time, cpas_s_time, cpas_e_time ,cbt_s_time, cbt_e_time, rcm_m_s_time, rcm_m_e_time, play_beliefs_s_time, play_beliefs_e_time, aspiration_s_time, aspiration_e_time, pss_s_time, pss_e_time))

```



## Have Different formate ,use one formate 


```{r}

Caregiver_36Months_data1 <- Caregiver_36Months_data %>%
  mutate(
    across(
      ends_with("_s_time") | ends_with("_s_t") | ends_with("_s_t_m"),
      ~ suppressWarnings(parse_date_time(
        as.character(.),
        orders = c("Y-m-d H-M", "Y-m-d H:M", "H:M:S p", "H:M p"),
        tz = "Asia/Dhaka"
      ))
    ),
    across(
      ends_with("_e_time") | ends_with("_e_t") | ends_with("_e_t_m"),
      ~ suppressWarnings(parse_date_time(
        as.character(.),
        orders = c("Y-m-d H-M", "Y-m-d H:M", "H:M:S p", "H:M p"),
        tz = "Asia/Dhaka"
      ))
    )
  )


```


## Keep only time section 


```{r}
library(dplyr)
library(stringr)

# List of time columns
time_cols <- c("education_s_t","education_e_t",
               "environment_s_t","environment_e_t",
               "asset_s_t","asset_e_t",
               "health_stat_s_t","health_stat_e_t",
               "ecdprograms_s_t","ecdprograms_e_t",
               "socialsup_s_t","socialsup_e_t",
               "mva_s_t_m","mva_e_t_m",
               "htq4_s_time","htq4_e_t",
               "function_s_t","function_e_t",
               "ref_function_s_t","ref_function_e_t",
               "psqi_s_t","psqi_e_t",
               "rmhm_s_t","rmhm_e_t",
               "stressors_s_time","stressors_e_time",
               "cpas_s_time","cpas_e_time",
               "cbt_s_time","cbt_e_time",
               "rcm_m_s_time","rcm_m_e_time",
               "play_beliefs_s_time","play_beliefs_e_time",
               "aspiration_s_time","aspiration_e_time",
               "pss_s_time","pss_e_time")

Caregiver_36Months_data1 <- Caregiver_36Months_data1 %>%
  mutate(across(all_of(time_cols),
                ~ str_extract(., "\\d{1,2}:\\d{2}:\\d{2}") ))  # extract HH:MM:SS



```




```{r}
View(Caregiver_36Months_data1 %>%
  select(education_s_t, education_e_t,
         environment_s_t, environment_e_t,
         asset_s_t, asset_e_t,
         health_stat_s_t, health_stat_e_t,
         ecdprograms_s_t, ecdprograms_e_t,
         socialsup_s_t, socialsup_e_t,
         mva_s_t_m, mva_e_t_m,
         htq4_s_time, htq4_e_t,
         function_s_t, function_e_t,
         ref_function_s_t, ref_function_e_t,
         psqi_s_t, psqi_e_t,
         rmhm_s_t, rmhm_e_t,
         stressors_s_time, stressors_e_time,
         cpas_s_time, cpas_e_time,
         cbt_s_time, cbt_e_time,
         rcm_m_s_time, rcm_m_e_time,
         play_beliefs_s_time, play_beliefs_e_time,
         aspiration_s_time, aspiration_e_time,
         pss_s_time, pss_e_time))

```



### Convert time section to date & time for duration 


```{r}
library(dplyr)
library(lubridate)
library(purrr)

start_cols <- c("education_s_t","environment_s_t","asset_s_t","health_stat_s_t",
                "ecdprograms_s_t","socialsup_s_t","mva_s_t_m","htq4_s_time",
                "function_s_t","ref_function_s_t","psqi_s_t","rmhm_s_t",
                "stressors_s_time","cpas_s_time","cbt_s_time","rcm_m_s_time",
                "play_beliefs_s_time","aspiration_s_time","pss_s_time")

end_cols <- c("education_e_t","environment_e_t","asset_e_t","health_stat_e_t",
              "ecdprograms_e_t","socialsup_e_t","mva_e_t_m","htq4_e_t",
              "function_e_t","ref_function_e_t","psqi_e_t","rmhm_e_t",
              "stressors_e_time","cpas_e_time","cbt_e_time","rcm_m_e_time",
              "play_beliefs_e_time","aspiration_e_time","pss_e_time")

duration_cols <- paste0(gsub("_s_t","",start_cols), "_duration")

Caregiver_36Months_data1 <- Caregiver_36Months_data1 %>%
  mutate(across(all_of(c(start_cols, end_cols)), ~ as.POSIXct(., format="%H:%M:%S", tz="Asia/Dhaka"))) 


```


## Duration Miniuts

```{r}
Caregiver_36Months_data1 <- Caregiver_36Months_data1 %>%
  mutate(
    education_duration = as.numeric(difftime(education_e_t, education_s_t, units = "mins")),
    environment_duration = as.numeric(difftime(environment_e_t, environment_s_t, units = "mins")),
    asset_duration = as.numeric(difftime(asset_e_t, asset_s_t, units = "mins")),
    health_stat_duration = as.numeric(difftime(health_stat_e_t, health_stat_s_t, units = "mins")),
    ecdprograms_duration = as.numeric(difftime(ecdprograms_e_t, ecdprograms_s_t, units = "mins")),
    socialsup_duration = as.numeric(difftime(socialsup_e_t, socialsup_s_t, units = "mins")),
    mva_duration = as.numeric(difftime(mva_e_t_m, mva_s_t_m, units = "mins")),
    htq4_duration = as.numeric(difftime(htq4_e_t, htq4_s_time, units = "mins")),
    function_duration = as.numeric(difftime(function_e_t, function_s_t, units = "mins")),
    ref_function_duration = as.numeric(difftime(ref_function_e_t, ref_function_s_t, units = "mins")),
    psqi_duration = as.numeric(difftime(psqi_e_t, psqi_s_t, units = "mins")),
    rmhm_duration = as.numeric(difftime(rmhm_e_t, rmhm_s_t, units = "mins")),
    stressors_duration = as.numeric(difftime(stressors_e_time, stressors_s_time, units = "mins")),
    cpas_duration = as.numeric(difftime(cpas_e_time, cpas_s_time, units = "mins")),
    cbt_duration = as.numeric(difftime(cbt_e_time, cbt_s_time, units = "mins")),
    rcm_m_duration = as.numeric(difftime(rcm_m_e_time, rcm_m_s_time, units = "mins")),
    play_beliefs_duration = as.numeric(difftime(play_beliefs_e_time, play_beliefs_s_time, units = "mins")),
    aspiration_duration = as.numeric(difftime(aspiration_e_time, aspiration_s_time, units = "mins")),
    pss_duration = as.numeric(difftime(pss_e_time, pss_s_time, units = "mins"))
  )

```


### Keep only duration miniuts & Merage main data set



```{r}
Caregiver_36Months_data1<-Caregiver_36Months_data1 %>% select(fcn_no,education_duration,environment_duration,asset_duration,health_stat_duration,ecdprograms_duration,socialsup_duration,mva_duration,htq4_duration,function_duration,ref_function_duration,psqi_duration,rmhm_duration,stressors_duration,cpas_duration,cbt_duration,rcm_m_duration,play_beliefs_duration,aspiration_duration,pss_duration)


#View(Caregiver_36Months_data1)

Caregiver_36Months_data<-Caregiver_36Months_data %>% full_join(Caregiver_36Months_data1,by="fcn_no")


```


## Show section start & end with duration miniuts

```{r}
# Automatically select all start, end, and duration columns
cols_to_view <- c(
  grep("_s_t$", names(Caregiver_36Months_data), value = TRUE),
  grep("_e_t$", names(Caregiver_36Months_data), value = TRUE),
  grep("_duration$", names(Caregiver_36Months_data), value = TRUE)
)



#View(Caregiver_36Months_data %>% select(all_of(cols_to_view)))

```


```{r}
View(
  Caregiver_36Months_data %>%
    select(survey_s_time,survey_e_time,duration_minutes,survey_date,enu,fcn_no,
      education_s_t, education_e_t, education_duration,
      environment_s_t, environment_e_t, environment_duration,
      asset_s_t, asset_e_t, asset_duration,
      health_stat_s_t, health_stat_e_t, health_stat_duration,
      ecdprograms_s_t, ecdprograms_e_t, ecdprograms_duration,
      socialsup_s_t, socialsup_e_t, socialsup_duration,
      mva_s_t_m, mva_e_t_m, mva_duration,
      htq4_s_time, htq4_e_t, htq4_duration,
      function_s_t, function_e_t, function_duration,
      ref_function_s_t, ref_function_e_t, ref_function_duration,
      psqi_s_t, psqi_e_t, psqi_duration,
      rmhm_s_t, rmhm_e_t, rmhm_duration,
      stressors_s_time, stressors_e_time, stressors_duration,
      cpas_s_time, cpas_e_time, cpas_duration,
      cbt_s_time, cbt_e_time, cbt_duration,
      rcm_m_s_time, rcm_m_e_time, rcm_m_duration,
      play_beliefs_s_time, play_beliefs_e_time, play_beliefs_duration,
      aspiration_s_time, aspiration_e_time, aspiration_duration,
      pss_s_time, pss_e_time, pss_duration
    )
)





library(writexl)

# Create a smaller dataset with your selected variables
Caregiver_36Months_subset <- Caregiver_36Months_data %>%
  select(
    survey_s_time, survey_e_time, duration_minutes, survey_date, enu, fcn_no,
    education_s_t, education_e_t, education_duration,
    environment_s_t, environment_e_t, environment_duration,
    asset_s_t, asset_e_t, asset_duration,
    health_stat_s_t, health_stat_e_t, health_stat_duration,
    ecdprograms_s_t, ecdprograms_e_t, ecdprograms_duration,
    socialsup_s_t, socialsup_e_t, socialsup_duration,
    mva_s_t_m, mva_e_t_m, mva_duration,
    htq4_s_time, htq4_e_t, htq4_duration,
    function_s_t, function_e_t, function_duration,
    ref_function_s_t, ref_function_e_t, ref_function_duration,
    psqi_s_t, psqi_e_t, psqi_duration,
    rmhm_s_t, rmhm_e_t, rmhm_duration,
    stressors_s_time, stressors_e_time, stressors_duration,
    cpas_s_time, cpas_e_time, cpas_duration,
    cbt_s_time, cbt_e_time, cbt_duration,
    rcm_m_s_time, rcm_m_e_time, rcm_m_duration,
    play_beliefs_s_time, play_beliefs_e_time, play_beliefs_duration,
    aspiration_s_time, aspiration_e_time, aspiration_duration,
    pss_s_time, pss_e_time, pss_duration
  )

# Load the package
library(writexl)
# Export to Excel file
#write_xlsx(Caregiver_36Months_subset, "Caregiver_36Months_duration_summary.xlsx")

# File will be saved in your working directory
#getwd()  # Run this to see where it was saved





```


### Count Persentage By Field Enumanator



```{r}
### Count Persentage By Field Enumanator

### Enviroment  Section

Caregiver_36Months_data %>% select(starts_with("prei"),enu) %>% tbl_summary(by="enu")

### Assest Section


Caregiver_36Months_data %>% select(chair_n,bed_n,fan_n,chicken_n,gold_w,gold_item,solarpanel_n,gascylinder_n,table_n,trunk_n,plasticddrum_n,otherasset_o,enu) %>% tbl_summary(by="enu")


### Health Section

Caregiver_36Months_data %>% select(preg_current,preg_current_week,preg_current_plan,preg_current_breastfeed,preg_current_newc,newc_age,preg_contraceptive,health_smoke,food_energy,food_energy_1,food_energy_2,food_energy_3,food_energy_4,food_energy_96,food_yesterday_1,food_yesterday_2,food_yesterday_3,food_yesterday_4,food_yesterday_5,food_yesterday_6,food_yesterday_7,food_yesterday_9,food_yesterday_10,food_yesterday_11,food_yesterday_11,food_yesterday_12,food_oth_grain,food_oth_starch,enu) %>% tbl_summary(by="enu")

### ECD Program

Caregiver_36Months_data %>% select(starts_with("ecd_map"),enu) %>% tbl_summary(by="enu")

### Vaccine Program

Caregiver_36Months_data %>% select(starts_with("vaccin"),enu) %>% tbl_summary(by="enu")

### socialsup Program

Caregiver_36Months_data %>% select(starts_with("socialsup"),enu) %>%select(-c(socialsup_s_t, socialsup_s_time, socialsup_e_time ,socialsup_e_t)) %>%  tbl_summary(by="enu")

### MVA Program

Caregiver_36Months_data %>% select(starts_with("mva"),enu) %>%select(-c(mva_e_t_m ,mva_e_time_m, mva_s_time_m, mva_s_t_m)) %>%  tbl_summary(by="enu")






```




```{r}
# Load required libraries
library(gtsummary)
library(tidyverse)
library(flextable)
library(officer)

# Simple function that works with your current data
create_supervisor_report <- function(data, output_file = "Supervisor_Report.pdf") {
  
  # Create a new Word document
  doc <- read_docx()
  
  # Title page
  doc <- doc %>%
    body_add_par("Supervisor Report: Summary Statistics by Field Enumerator", 
                 style = "heading 1") %>%
    body_add_par(paste("Generated on:", format(Sys.Date(), "%B %d, %Y")), 
                 style = "Normal") %>%
    body_add_par("") %>%
    body_add_par("")
  
  # Environment Section
  doc <- doc %>%
    body_add_par("1. Environment Section", style = "heading 2")
  
  env_table <- data %>%
    select(starts_with("prei"), enu) %>%
    tbl_summary(by = "enu") %>%
    as_flex_table()
  
  doc <- doc %>%
    body_add_flextable(env_table) %>%
    body_add_par("") %>%
    body_page_break()
  
  # Assets Section
  doc <- doc %>%
    body_add_par("2. Assets Section", style = "heading 2")
  
  assets_table <- data %>%
    select(chair_n, bed_n, fan_n, chicken_n, gold_w, gold_item, solarpanel_n, 
           gascylinder_n, table_n, trunk_n, plasticddrum_n, otherasset_o, enu) %>%
    tbl_summary(by = "enu") %>%
    as_flex_table()
  
  doc <- doc %>%
    body_add_flextable(assets_table) %>%
    body_add_par("") %>%
    body_page_break()
  
  # Health Section
  doc <- doc %>%
    body_add_par("3. Health Section", style = "heading 2")
  
  health_table <- data %>%
    select(preg_current, preg_current_week, preg_current_plan, preg_current_breastfeed,
           preg_current_newc, newc_age, preg_contraceptive, health_smoke, food_energy,
           food_energy_1, food_energy_2, food_energy_3, food_energy_4, food_energy_96,
           food_yesterday_1, food_yesterday_2, food_yesterday_3, food_yesterday_4,
           food_yesterday_5, food_yesterday_6, food_yesterday_7, food_yesterday_9,
           food_yesterday_10, food_yesterday_11, food_yesterday_12, food_oth_grain,
           food_oth_starch, enu) %>%
    tbl_summary(by = "enu") %>%
    as_flex_table()
  
  doc <- doc %>%
    body_add_flextable(health_table) %>%
    body_add_par("") %>%
    body_page_break()
  
  # ECD Program Section
  doc <- doc %>%
    body_add_par("4. ECD Program", style = "heading 2")
  
  ecd_table <- data %>%
    select(starts_with("ecd_map"), enu) %>%
    tbl_summary(by = "enu") %>%
    as_flex_table()
  
  doc <- doc %>%
    body_add_flextable(ecd_table) %>%
    body_add_par("") %>%
    body_page_break()
  
  # Vaccine Program Section
  doc <- doc %>%
    body_add_par("5. Vaccine Program", style = "heading 2")
  
  vaccine_table <- data %>%
    select(starts_with("vaccin"), enu) %>%
    tbl_summary(by = "enu") %>%
    as_flex_table()
  
  doc <- doc %>%
    body_add_flextable(vaccine_table) %>%
    body_add_par("") %>%
    body_page_break()
  
  # Social Support Program Section
  doc <- doc %>%
    body_add_par("6. Social Support Program", style = "heading 2")
  
  socialsup_table <- data %>%
    select(starts_with("socialsup"), enu) %>%
    select(-c(socialsup_s_t, socialsup_s_time, socialsup_e_time, socialsup_e_t)) %>%
    tbl_summary(by = "enu") %>%
    as_flex_table()
  
  doc <- doc %>%
    body_add_flextable(socialsup_table) %>%
    body_add_par("") %>%
    body_page_break()
  
  # MVA Program Section
  doc <- doc %>%
    body_add_par("7. MVA Program", style = "heading 2")
  
  mva_table <- data %>%
    select(starts_with("mva"), enu) %>%
    select(-c(mva_e_t_m, mva_e_time_m, mva_s_time_m, mva_s_t_m)) %>%
    tbl_summary(by = "enu") %>%
    as_flex_table()
  
  doc <- doc %>%
    body_add_flextable(mva_table)
  
  # Save as PDF
  print(doc, target = output_file)
  
  message("PDF report generated successfully: ", output_file)
}

# Alternative: Create individual tables and save as separate files
create_individual_tables <- function(data) {
  
  # Create output directory
  dir.create("supervisor_tables", showWarnings = FALSE)
  
  # Environment Section
  env_table <- data %>%
    select(starts_with("prei"), enu) %>%
    tbl_summary(by = "enu")
  
  # Assets Section
  assets_table <- data %>%
    select(chair_n, bed_n, fan_n, chicken_n, gold_w, gold_item, solarpanel_n, 
           gascylinder_n, table_n, trunk_n, plasticddrum_n, otherasset_o, enu) %>%
    tbl_summary(by = "enu")
  
  # Health Section
  health_table <- data %>%
    select(preg_current, preg_current_week, preg_current_plan, preg_current_breastfeed,
           preg_current_newc, newc_age, preg_contraceptive, health_smoke, food_energy,
           food_energy_1, food_energy_2, food_energy_3, food_energy_4, food_energy_96,
           food_yesterday_1, food_yesterday_2, food_yesterday_3, food_yesterday_4,
           food_yesterday_5, food_yesterday_6, food_yesterday_7, food_yesterday_9,
           food_yesterday_10, food_yesterday_11, food_yesterday_12, food_oth_grain,
           food_oth_starch, enu) %>%
    tbl_summary(by = "enu")
  
  # ECD Program
  ecd_table <- data %>%
    select(starts_with("ecd_map"), enu) %>%
    tbl_summary(by = "enu")
  
  # Vaccine Program
  vaccine_table <- data %>%
    select(starts_with("vaccin"), enu) %>%
    tbl_summary(by = "enu")
  
  # Social Support Program
  socialsup_table <- data %>%
    select(starts_with("socialsup"), enu) %>%
    select(-c(socialsup_s_t, socialsup_s_time, socialsup_e_time, socialsup_e_t)) %>%
    tbl_summary(by = "enu")
  
  # MVA Program
  mva_table <- data %>%
    select(starts_with("mva"), enu) %>%
    select(-c(mva_e_t_m, mva_e_time_m, mva_s_time_m, mva_s_t_m)) %>%
    tbl_summary(by = "enu")
  
  # Save individual tables
  env_table %>% as_flex_table() %>% save_as_docx(path = "supervisor_tables/01_environment.docx")
  assets_table %>% as_flex_table() %>% save_as_docx(path = "supervisor_tables/02_assets.docx")
  health_table %>% as_flex_table() %>% save_as_docx(path = "supervisor_tables/03_health.docx")
  ecd_table %>% as_flex_table() %>% save_as_docx(path = "supervisor_tables/04_ecd.docx")
  vaccine_table %>% as_flex_table() %>% save_as_docx(path = "supervisor_tables/05_vaccine.docx")
  socialsup_table %>% as_flex_table() %>% save_as_docx(path = "supervisor_tables/06_social_support.docx")
  mva_table %>% as_flex_table() %>% save_as_docx(path = "supervisor_tables/07_mva.docx")
  
  message("Individual tables saved in 'supervisor_tables' folder")
}

# Quick function for HTML output (often more reliable)
create_html_report <- function(data, output_file = "Supervisor_Report.html") {
  
  # Create all tables
  tables_list <- list(
    Environment = data %>% select(starts_with("prei"), enu) %>% tbl_summary(by = "enu"),
    Assets = data %>% select(chair_n, bed_n, fan_n, chicken_n, gold_w, gold_item, solarpanel_n, 
                            gascylinder_n, table_n, trunk_n, plasticddrum_n, otherasset_o, enu) %>% tbl_summary(by = "enu"),
    Health = data %>% select(preg_current, preg_current_week, preg_current_plan, preg_current_breastfeed,
                            preg_current_newc, newc_age, preg_contraceptive, health_smoke, food_energy,
                            food_energy_1, food_energy_2, food_energy_3, food_energy_4, food_energy_96,
                            food_yesterday_1, food_yesterday_2, food_yesterday_3, food_yesterday_4,
                            food_yesterday_5, food_yesterday_6, food_yesterday_7, food_yesterday_9,
                            food_yesterday_10, food_yesterday_11, food_yesterday_12, food_oth_grain,
                            food_oth_starch, enu) %>% tbl_summary(by = "enu"),
    ECD = data %>% select(starts_with("ecd_map"), enu) %>% tbl_summary(by = "enu"),
    Vaccine = data %>% select(starts_with("vaccin"), enu) %>% tbl_summary(by = "enu"),
    SocialSupport = data %>% select(starts_with("socialsup"), enu) %>% 
      select(-c(socialsup_s_t, socialsup_s_time, socialsup_e_time, socialsup_e_t)) %>% 
      tbl_summary(by = "enu"),
    MVA = data %>% select(starts_with("mva"), enu) %>% 
      select(-c(mva_e_t_m, mva_e_time_m, mva_s_time_m, mva_s_t_m)) %>% 
      tbl_summary(by = "enu")
  )
  
  # Combine into one table
  combined_table <- tbl_merge(
    tbls = tables_list,
    tab_spanner = names(tables_list)
  )
  
  # Save as HTML
  combined_table %>% 
    as_gt() %>%
    gt::gtsave(filename = output_file)
  
  message("HTML report generated: ", output_file)
}
```






```{r}

```























