---
title: "Data Cleaning"
author: "Mukter"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
# Installing packages
list.of.packages <- c("foreign", "psych", "reshape2", "dplyr", "ggplot2","tidyr", 
                      "haven", "readxl", "tidyverse","dplR","gtsummary","gt","lubridate","officer","rmarkdown","gtExtras","flextable",
                      "openxlsx", "Hmisc", "janitor", "lme4", "ggsci", "ggpubr", "lmerTest", "sjPlot", "sjmisc", "sjlabelled", "labelled", "codebook", "report", "data.table", "jcolors", "lessR", "lmeresampler", "MuMIn", "caret", "coefplot", "modelbased", "report", "see","effectsize", "performance", "parameters")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
# Loading packages
lapply(list.of.packages, require, character.only = TRUE)




```

```{r}


library(readxl)
library(foreign)
library(haven)
library(dplR)
library(tidyverse)
library(labelled)
library(gtsummary)
library(gt)
library(lubridate)
library(gt)
library(dplyr)
library(openxlsx)
library(officer)
library(flextable)
library(rmarkdown)
library(knitr)
library(psych)
library(ggplot2)
library(lubridate)
library(labelled)
library(haven)

```


### Data set open


```{r}
#F:NYU_data/Raw/Physio_NYU_36Months_draft_WIDE

physio_data<-read_dta("H:/.shortcut-targets-by-id/10GfELvbVWTnThBtJs-WKEAmKwWDCBjeu/Clean Dataset/2_Data_file/Physio_NYU_data.dta")

```



```{r}
# describe the data set
#describe(physio_data)
glimpse(physio_data)
```

### Pailot Data

```{r}
#C:\Users\icddrb\Downloads/Pailot_Bio

# Read sheet 2 by name
pailot_data <- read_excel("C:/Users/icddrb/Downloads/Pailot_Bio.xlsx", sheet = 2)
view(pailot_data)


pailot_data <- pailot_data %>% dplyr::rename(fcn_number = `FCN_no/HHID`)


```


```{r}
# Check for character vs numeric issues
pailot_data <- pailot_data %>% mutate(fcn_no = as.character(fcn_number))
physio_data <- physio_data %>% mutate(fcn_no = as.character(fcn_no))

### Duplicated check
# duplicated(pailot_data$fcn_number)
# duplicated(physio_data$fcn_no)

 
### Use duplicated data set 
 # Check for completely duplicated rows
#sum(duplicated(physio_data$fcn_no))

# View the duplicated rows
#physio_data[duplicated(physio_data$fcn_no), ]
 

```


### Join The data set

```{r}


# Then try joining again
join_data <- left_join(pailot_data, physio_data, by = c("fcn_no" = "fcn_no"))

## View 

#view(join_data)

```




#Total duration Minuts of the survey

```{r}
# If you want to verify the conversion and see all components
join_data <- join_data %>%
  mutate(
    start_datetime = mdy_hms(starttime),
    end_datetime = mdy_hms(endtime),
    
    # Extract date and time components for verification
    start_date = as.Date(start_datetime),
    start_time = format(start_datetime, "%H:%M:%S"),
    end_date = as.Date(end_datetime),
    end_time = format(end_datetime, "%H:%M:%S"),
    
    # Calculate duration
    duration_minutes = as.numeric(difftime(end_datetime, start_datetime, units = "mins")),
    
    # Also calculate duration in hours and seconds if needed
    duration_hours = duration_minutes / 60
)     

# View the detailed results
join_data %>% select(starttime, endtime, duration_minutes, duration_hours)
```




          



```{r}
##### All section duration time 

join_data <- join_data %>%
  mutate(
    # Convert times and handle cases where end time might be after midnight
    food_start = as.POSIXct(food_s_time, format = "%I:%M:%S %p"),
    food_end = as.POSIXct(food_e_time, format = "%I:%M:%S %p"),
    saliva_start = as.POSIXct(saliva_s_time, format = "%I:%M:%S %p"),
    saliva_end = as.POSIXct(saliva_e_time, format = "%I:%M:%S %p"),
    chronic_start = as.POSIXct(chronic_s_time, format = "%I:%M:%S %p"),
    chronic_end = as.POSIXct(chronic_e_time, format = "%I:%M:%S %p"),
    current_start = as.POSIXct(current_s_time, format = "%I:%M:%S %p"),
    current_end = as.POSIXct(current_e_time, format = "%I:%M:%S %p"),  # Fixed: current_e_time
    body_start = as.POSIXct(body_es_st, format = "%I:%M:%S %p"),  # Check if this is correct or if you need separate start/end
    body_end = as.POSIXct(body_es_et, format = "%I:%M:%S %p"),    # Same issue - probably need body_es and body_et

    body_m_o_start = as.POSIXct(bgmom_only_s_t, format = "%I:%M:%S %p"),
    body_m_o_end = as.POSIXct(bgmom_only_e_t, format = "%I:%M:%S %p"),    
    body_mc_start = as.POSIXct(bgmc_bas_toge_s_t, format = "%I:%M:%S %p"),
    body_mc_end = as.POSIXct(bgmc_bas_toge_e_t, format = "%I:%M:%S %p"),    
    body_c_o_start = as.POSIXct(bgmc_bas_apart_s_t, format = "%I:%M:%S %p"),
    body_c_o_end = as.POSIXct(bgmc_bas_apart_e_t, format = "%I:%M:%S %p"),
    ccio_start = as.POSIXct(ccio_s_t, format = "%I:%M:%S %p"),
    ccio_end = as.POSIXct(ccio_e_t, format = "%I:%M:%S %p"),

    ccio_duration_minutes = as.numeric(difftime(ccio_end, ccio_start, units = "mins")),  
    # Calculate durations - FIXED PAIRS:
    food_duration_minutes = as.numeric(difftime(food_end, food_start, units = "mins")),  # Fixed: food_end vs food_start
    saliva_duration_minutes = as.numeric(difftime(saliva_end, saliva_start, units = "mins")),
    chronic_duration_minutes = as.numeric(difftime(chronic_end, chronic_start, units = "mins")),
    current_duration_minutes = as.numeric(difftime(current_end, current_start, units = "mins")),
    body_duration_tot_minutes = as.numeric(difftime(body_end, body_start, units = "mins")),
    body_duration_mo_minutes = as.numeric(difftime(body_m_o_end, body_m_o_start, units = "mins")),  # Fixed: consistent naming
    body_duration_mc_minutes = as.numeric(difftime(body_mc_end, body_mc_start, units = "mins")),    # Fixed: consistent naming
    body_duration_co_minutes = as.numeric(difftime(body_c_o_end, body_c_o_start, units = "mins"))    # Fixed: consistent naming
  )

```






```{r}

Mother_join_data<-join_data %>% filter(respondent_cat==10)
child_join_data<-join_data %>% filter(respondent_cat==101)


```

################# Mohter Data


```{r}
View(Mother_join_data %>% select(fcn_number,enu,food_duration_minutes,saliva_duration_minutes,chronic_duration_minutes,current_duration_minutes,body_duration_tot_minutes,body_duration_mo_minutes,body_m_o_start,body_m_o_end,body_duration_mc_minutes,body_mc_start,body_mc_end,body_duration_co_minutes,ccio_duration_minutes,duration_minutes,starttime, endtime))

View(Mother_join_data %>% select(body_m_o_start,body_m_o_end,body_duration_mo_minutes,fcn_number))


```

#Duplicates Check

```{r}
# fcn Number
Mother_join_data %>%
  select(fcn_number,enu, saliva_id, survey_date) %>% 
  mutate(
    is_first_occurrence = !duplicated(fcn_number),
    is_duplicate = duplicated(fcn_number)
  ) %>%
  filter(is_duplicate | duplicated(fcn_number, fromLast = TRUE)) %>%
  View()


### Saliva ID 

join_data %>%
  select(fcn_number,enu, saliva_id, survey_date) %>% 
  mutate(
    is_first_occurrence = !duplicated(saliva_id),
    is_duplicate = duplicated(saliva_id)
  ) %>%
  filter(is_duplicate | duplicated(saliva_id, fromLast = TRUE)) %>%
  View()

### PID

Mother_join_data %>%
  select(fcn_number, pid, enu, PID, survey_date) %>% 
  mutate(
    is_first_occurrence = !duplicated(pid),
    is_duplicate = duplicated(pid)
  ) %>%
  filter(is_duplicate | duplicated(pid, fromLast = TRUE)) %>%
  View()



View(Mother_join_data %>%select(saliva_id,Saliva_ID...40))
#View(Mother_join_data %>%select(pid,PID))

```


#### Analysis Of the Mother Physio Data

```{r}

Mother_physio<-physio_data %>% filter(respondent_cat==10)

```

### Table Summary


```{r}
Mother_physio %>% select(restype,res_age,drink_tea_1,brush_teeth_1,dental_work_1,any_medicine_1,oral_injury_1,betel_leaf_1,smoke_1,chronic_disease_1_1,chronic_disease_2_1,chronic_disease_3_1,chronic_disease_4_1,chronic_disease_5_1,chronic_disease_6_1,chronic_disease_7_1,chronic_disease_8_1,chronic_disease_9_1,chronic_disease_oth_1,current_disease_1_1,current_disease_2_1,current_disease_3_1,current_disease_4_1,current_disease_5_1,current_disease_6_1,current_disease_8_1,current_disease_9_1,current_disease_10_1,current_disease_11_1,current_disease_12_1,current_disease_13_1,current_disease_other_1,systolic_pressure_1,diastolic_pressure_1,systolic_pressure_2,diastolic_pressure_2,any_illness_1,any_illness_2,any_illness_3,any_illness_4,any_illness_5,any_illness_6,any_illness_oth) %>% tbl_summary()
```



```{r}
library(gtsummary)
library(dplyr)

Mother_physio %>%
  select(
    restype, res_age, drink_tea_1, brush_teeth_1, dental_work_1, any_medicine_1,
    oral_injury_1, betel_leaf_1, smoke_1, chronic_disease_1_1, chronic_disease_2_1,
    chronic_disease_3_1, chronic_disease_4_1, chronic_disease_5_1, chronic_disease_6_1,
    chronic_disease_7_1, chronic_disease_8_1, chronic_disease_9_1, chronic_disease_oth_1,
    current_disease_1_1, current_disease_2_1, current_disease_3_1, current_disease_4_1,
    current_disease_5_1, current_disease_6_1, current_disease_8_1, current_disease_9_1,
    current_disease_10_1, current_disease_11_1, current_disease_12_1, current_disease_13_1,
    current_disease_other_1, systolic_pressure_1, diastolic_pressure_1,
    systolic_pressure_2, diastolic_pressure_2, any_illness_1, any_illness_2,
    any_illness_3, any_illness_4, any_illness_5, any_illness_6, any_illness_oth
  ) %>%
  tbl_summary(
    type = list(where(is.numeric) ~ "continuous", where(is.factor) ~ "categorical"),
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} ({p}%)"
    ),
    digits = all_continuous() ~ 1  # round mean & sd to 1 decimal
  ) %>%
  modify_header(label = "**Characteristic**") %>%
  modify_spanning_header(all_stat_cols() ~ "**N = {N}**") %>%
  bold_labels()

```






### Duration Miniuts

```{r}

# Convert to POSIXct and calculate duration
Mother_join_data <- Mother_join_data %>%
  mutate(
    survey_s_time = parse_date_time(survey_s_time, orders = "I:M:S p"),
    survey_e_time = parse_date_time(survey_e_time, orders = "I:M:S p"),
    duration_minutes = as.numeric(difftime(survey_e_time, survey_s_time, units = "mins"))
  )




View(Mother_join_data %>% select(survey_s_time,survey_e_time,duration_minutes))


```







```{r}
Mother_join_data %>%
  select(food_duration_minutes,
         saliva_duration_minutes,
         chronic_duration_minutes,
         current_duration_minutes,
         body_duration_tot_minutes,
         body_duration_mo_minutes,
         body_duration_mc_minutes,
         body_duration_co_minutes,
         ccio_duration_minutes,
         duration_minutes) %>%
  tbl_summary(
    type = list(where(is.numeric) ~ "continuous",
                where(is.factor) ~ "categorical"),
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} ({p}%)"
    )
  ) %>%
  modify_header(label = "**Characteristic**") %>%
  modify_spanning_header(all_stat_cols() ~ "**N = {N}**") %>%
  bold_labels()
```





























